### ISSUE TITLE
What languages does this support? And can it do literal matching only?

### ISSUE THREAD

**Issue by StingyJack** [codesearch-github/codesearch#85]
Specifically looking to see if it can do c#, python, js/ts, html, xml or if its just Java (the only mentioned language, but that mention is about the lang the program is written in).

For the search an example would be if I have a sql stored procedure script that references a table named `A2B_LookAtThisTableNames`   and I search for "A2B_LookAtThisTableNames" or "LookatthisTablename" or just "A2B_L"  will this return the stored proc script in the results?  Will a search for "decry" find "Decrypt"?

**Comment by david-froehlich** [comment]
We differentiate between code-analysis and plain text-search.
**plain-text-search** is filetype and language agnostic and **should work for all text-based files**.
the plain-text-search is used for the regular search function and can be seen [http://codesearch.sourceforge.net/img/screens/searcher.jpg](here).
The plain text search allows wildcards and case-sensitive/insensitive search.  So the examples from your issue should be possible.

**code-analysis** is used when displaying a file to show an outline, usages, etc. and is **only available for Java and XML**
see http://codesearch.sourceforge.net/img/screens/file_view.jpg for an example.
code-analysis also adds some extra fields to the search. it is possible to search for 

Do note however, that this project has not been maintained in many years. If you decide to use it and run into issues do not hesitate to post here. If necessary we would be happy to maintain this project more actively.
